import {StyleSheet} from "react-native";

export const recipeStyles = StyleSheet.create({
  recipeListContainer: {
    flex: 1,
  },
  recipeItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 140,
    borderColor: '#da3c3c',
    borderWidth: 1,
    borderRadius: 10,
    margin: 10,
  },
  recipeItemImage: {
    flex: 1,
    height: '95%',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 10,
    marginLeft: 5,
  },
  recipeItemInfo: {
    height: '95%',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderWidth: 1,
  },
  recipeItemPercent: {
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 10,
    width: 50,
    height: 50,
    margin: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  recipeItemUser: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    height: '15%',
    width: '100%',
    borderWidth: 1,
    flexDirection: 'row',
  },
  recipeItemTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  recipeItemTitleContainer: {
    alignItems: 'center',
    justifyContent:'center',
    height: '45%',
    borderWidth: 1,
    width: '100%',
  },
  recipeItemInfoContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  singleRecipeInfoContainer: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    marginLeft: 5,
  },
  recipeInfoText: {
    fontSize: 15,
    marginLeft: 5,
  },
  recipeFavoriteContainer: {
    backgroundColor: 'rgba(217, 217, 217, 0.50)',
    width: 30,
    height: 30,
    position: 'relative',
    top: 5,
    left: 5,
    borderRadius: 99,
    alignItems: 'center',
    justifyContent:'center',
  },
})
